dist: xenial

language: python
cache: pip

addons: 
  sonarcloud:
    organization: jy-ying 
    token:
      secure: ••••••••••••••••
env:
  global:
    - CC_TEST_REPORTER_ID=$TEST_REPORTER_ID
    
python:
- 3.8.1
  
  install:
  - pip install -e .
  - pip install ."[tests]"
  - pip install coverage
  - pip install codeclimate-test-reporter
  - pip install pytest-cov

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - ./publish_via_travis.sh
  - py.test --cov=tests tests/
  - coverage xml
  - sonar-scanner
  
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - ./cc-test-reporter format-coverage -t coverage.py
  - ./cc-test-reporter upload-coverage
#   - ./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.backend.json coverage/backend/.resultset.json # Format backend coverage
#   - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.frontend.json coverage/frontend/lcov.info  # Format frontend coverage
#   - ./cc-test-reporter sum-coverage coverage/codeclimate.*.json -p 2                  # Sum both coverage parts into coverage/codeclimate.json
#   - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage --a199ef9c62ad2ca8c1f520bfe950eeeda67ed4ad08ece334514a0244a1da9ff2; fi  # Upload coverage/codeclimate.json

