dist: xenial


language: python
cache: pip

python:
- 3.8.1
env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1
    - CC_TEST_REPORTER_ID=$TEST_REPORTER_ID
    
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  
install:
- pip install --upgrade pip tox
- pip install ".[test]" 

script:
- tox
- sonar-scanner
- pytest
 
jobs:
  include:
    - env: TOXENV=py
    - env: TOXENV=docs
    - env: TOXENV=style
    - stage: Crowdin Deployment
      if: tag IS present OR ENV(BUILD_CROWDIN)
      python: 3.8.1
      env:
        - DEPLOYING=true
        - TOXENV=py38
      before_deploy:
      - curl https://artifacts.crowdin.com/repo/GPG-KEY-crowdin | sudo apt-key add -
      - echo "deb https://artifacts.crowdin.com/repo/deb/ /" | sudo tee -a /etc/apt/sources.list
      - sudo apt-get update -qq
      - sudo apt-get install -y crowdin
      - pip install redgettext==3.1
      deploy:
      - provider: script
        script: make upload_translations
        skip_cleanup: true
        on:
          repo: Cog-Creators/Red-DiscordBot
          tags: true
 
 after_success:
  - codecov
